FROM python:3.7
COPY ktrain_requirements.txt app/
COPY ktrain_answer_web.py app/
COPY ktrain_answer_web.css app/
COPY ktrain_init.py app/
COPY txt/* txt/
RUN pip install -r app/ktrain_requirements.txt && python app/ktrain_init.py
CMD streamlit run app/ktrain_answer_web.py